apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nico-rest-mock-core.fullname" . }}-config
  labels:
    {{- include "nico-rest-mock-core.labels" . | nindent 4 }}
data:
  {{ .Values.config.fileName }}: |
{{ .Values.config.machines | indent 4 }}
