//go:build ignore

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/NVIDIA/infra-controller/rest-api/site-workflow/pkg/grpc/mockdata"
	"google.golang.org/protobuf/encoding/protojson"
	"gopkg.in/yaml.v3"
)

const (
	defaultSegmentID = "00000000-0000-4000-9000-000000000000"
	valuesPath       = "helm/nico-rest-mock-core/values.yaml"
	valuesHeaderPath = "helm/nico-rest-mock-core/values.header.yaml"
	renderedPath     = "helm/nico-rest-mock-core/rendered/machines.yaml"
)

type inventory struct {
	Machines         []machineSpec         `yaml:"machines"`
	ExpectedMachines []expectedMachineSpec `yaml:"expected_machines,omitempty"`
}

type machineSpec struct {
	ID            string          `yaml:"id"`
	State         string          `yaml:"state"`
	Interfaces    []interfaceSpec `yaml:"interfaces"`
	DiscoveryInfo map[string]any  `yaml:"discovery_info"`
}

type interfaceSpec struct {
	Hostname         string   `yaml:"hostname"`
	MACAddress       string   `yaml:"mac_address"`
	Addresses        []string `yaml:"addresses"`
	SegmentID        string   `yaml:"segment_id"`
	PrimaryInterface bool     `yaml:"primary_interface"`
}

type expectedMachineSpec struct{}

func main() {
	inv := buildInventory()
	if err := writeRenderedMachines(inv); err != nil {
		panic(err)
	}
	if err := updateValuesInventory(inv); err != nil {
		panic(err)
	}
	fmt.Println("updated", valuesPath)
	fmt.Println("wrote", renderedPath)
}

func buildInventory() inventory {
	inv := inventory{}
	for hostID := 0; hostID < mockdata.MockHostCount; hostID++ {
		discovery, err := discoveryInfoMap(hostID)
		if err != nil {
			panic(err)
		}
		inv.Machines = append(inv.Machines, machineSpec{
			ID:    mockdata.MockMachineID(hostID),
			State: "Ready",
			Interfaces: []interfaceSpec{{
				Hostname:         mockdata.MockHostname(hostID),
				MACAddress:       fmt.Sprintf("58:a2:e1:5b:d1:%02x", 0xb0+hostID),
				Addresses:        []string{fmt.Sprintf("10.10.0.%d", 10+hostID)},
				SegmentID:        defaultSegmentID,
				PrimaryInterface: true,
			}},
			DiscoveryInfo: discovery,
		})
	}
	return inv
}

func discoveryInfoMap(hostID int) (map[string]any, error) {
	info := mockdata.MachineDiscoveryInfoForHost(hostID)
	raw, err := protojson.MarshalOptions{UseProtoNames: false}.Marshal(info)
	if err != nil {
		return nil, err
	}
	out := map[string]any{}
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func writeRenderedMachines(inv inventory) error {
	if err := os.MkdirAll(filepath.Dir(renderedPath), 0o755); err != nil {
		return err
	}
	data, err := yaml.Marshal(inv)
	if err != nil {
		return err
	}
	header := []byte("# Generated by scripts/gen-discovery/main.go — do not edit.\n")
	return os.WriteFile(renderedPath, append(header, data...), 0o644)
}

func updateValuesInventory(inv inventory) error {
	header, err := os.ReadFile(valuesHeaderPath)
	if err != nil {
		return err
	}
	invDoc, err := yaml.Marshal(map[string]any{"inventory": inv})
	if err != nil {
		return err
	}
	out := append(header, invDoc...)
	return os.WriteFile(valuesPath, out, 0o644)
}
