//go:build ignore

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/NVIDIA/infra-controller/rest-api/site-workflow/pkg/grpc/mockdata"
	"google.golang.org/protobuf/encoding/protojson"
	"gopkg.in/yaml.v3"
)

const (
	defaultSegmentID = "00000000-0000-4000-9000-000000000000"
	valuesPath       = "helm/nico-rest-mock-core/values.yaml"
	valuesHeaderPath = "helm/nico-rest-mock-core/values.header.yaml"
	renderedPath     = "helm/nico-rest-mock-core/rendered/machines.yaml"
)

type inventory struct {
	Machines         []machineSpec         `yaml:"machines"`
	ExpectedMachines []expectedMachineSpec `yaml:"expected_machines,omitempty"`
}

type machineSpec struct {
	ID                  string                   `yaml:"id"`
	State               string                   `yaml:"state"`
	Interfaces          []interfaceSpec          `yaml:"interfaces"`
	DiscoveryInfo       map[string]any           `yaml:"discovery_info"`
	MachineCapabilities []machineCapabilitySpec  `yaml:"machine_capabilities"`
}

type machineCapabilitySpec struct {
	Type       string `yaml:"type"`
	Name       string `yaml:"name"`
	Vendor     string `yaml:"vendor,omitempty"`
	Count      int    `yaml:"count"`
	Frequency  string `yaml:"frequency,omitempty"`
	Capacity   string `yaml:"capacity,omitempty"`
	DeviceType string `yaml:"device_type,omitempty"`
}

var mockCapabilities = []machineCapabilitySpec{
	{Type: "CPU", Name: "AMD EPYC 9115 16-Core Processor", Vendor: "AuthenticAMD", Count: 1},
	{Type: "DPU", Name: "DPU", Count: 1},
	{Type: "Network", Name: "I350 Gigabit Network Connection", Vendor: "Intel Corporation", Count: 2},
	{Type: "Network", Name: "MT43244 BlueField-3 integrated ConnectX-7 network controller", Vendor: "Mellanox Technologies", Count: 1, DeviceType: "DPU"},
	{Type: "Storage", Name: "SAMSUNG MZQL21T9HCJR-00A07", Count: 4},
	{Type: "GPU", Name: "NVIDIA A30", Frequency: "930 MHz", Capacity: "24576 MiB", Count: 1},
	{Type: "Memory", Name: "DDR5", Capacity: "262144 MB", Count: 1},
	{Type: "InfiniBand", Name: "MT28800 Family [ConnectX-5 Ex]", Vendor: "Mellanox Technologies", Count: 2},
	{Type: "Storage", Name: "SAMSUNG MZQL23T8HCLS-00A07", Count: 8},
	{Type: "Storage", Name: "SAMSUNG MZQL2960HCJR-00A07", Count: 2},
}

type interfaceSpec struct {
	Hostname         string   `yaml:"hostname"`
	MACAddress       string   `yaml:"mac_address"`
	Addresses        []string `yaml:"addresses"`
	SegmentID        string   `yaml:"segment_id"`
	PrimaryInterface bool     `yaml:"primary_interface"`
}

type expectedMachineSpec struct{}

func main() {
	inv := buildInventory()
	if err := writeRenderedMachines(inv); err != nil {
		panic(err)
	}
	if err := updateValuesInventory(inv); err != nil {
		panic(err)
	}
	fmt.Println("updated", valuesPath)
	fmt.Println("wrote", renderedPath)
}

func buildInventory() inventory {
	inv := inventory{}
	for hostID := 0; hostID < mockdata.MockHostCount; hostID++ {
		discovery, err := discoveryInfoMap(hostID)
		if err != nil {
			panic(err)
		}
		inv.Machines = append(inv.Machines, machineSpec{
			ID:    mockdata.MockMachineID(hostID),
			State: "Ready",
			Interfaces: []interfaceSpec{{
				Hostname:         mockdata.MockHostname(hostID),
				MACAddress:       fmt.Sprintf("58:a2:e1:5b:d1:%02x", 0xb0+hostID),
				Addresses:        []string{fmt.Sprintf("10.10.0.%d", 10+hostID)},
				SegmentID:        defaultSegmentID,
				PrimaryInterface: true,
			}},
			DiscoveryInfo:       discovery,
			MachineCapabilities: mockCapabilities,
		})
	}
	return inv
}

func discoveryInfoMap(hostID int) (map[string]any, error) {
	info := mockdata.MachineDiscoveryInfoForHost(hostID)
	raw, err := protojson.MarshalOptions{UseProtoNames: false}.Marshal(info)
	if err != nil {
		return nil, err
	}
	out := map[string]any{}
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func writeRenderedMachines(inv inventory) error {
	if err := os.MkdirAll(filepath.Dir(renderedPath), 0o755); err != nil {
		return err
	}
	data, err := yaml.Marshal(inv)
	if err != nil {
		return err
	}
	header := []byte("# Generated by scripts/gen-discovery/main.go — do not edit.\n")
	return os.WriteFile(renderedPath, append(header, data...), 0o644)
}

func updateValuesInventory(inv inventory) error {
	header, err := os.ReadFile(valuesHeaderPath)
	if err != nil {
		return err
	}
	invDoc, err := yaml.Marshal(map[string]any{"inventory": inv})
	if err != nil {
		return err
	}
	out := append(header, invDoc...)
	return os.WriteFile(valuesPath, out, 0o644)
}
